// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0-CjBTM2eYFyARXvafcXbSBWNgIiKs4',
    appId: '1:593815115508:web:cc54c7c026a9e3aa8d70a1',
    messagingSenderId: '593815115508',
    projectId: 'fitcare-6fc88',
    authDomain: 'fitcare-6fc88.firebaseapp.com',
    storageBucket: 'fitcare-6fc88.firebasestorage.app',
    measurementId: 'G-F2G7LDKQMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13AoKWj0QDPOi0ZXQ_cg-zS5owcnHQQE',
    appId: '1:593815115508:android:2f509003bdbde01a8d70a1',
    messagingSenderId: '593815115508',
    projectId: 'fitcare-6fc88',
    storageBucket: 'fitcare-6fc88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNgs-uKahUukr_KnMCdS-9Wt4oMEZnSY',
    appId: '1:593815115508:ios:f17bf181f96f6ed58d70a1',
    messagingSenderId: '593815115508',
    projectId: 'fitcare-6fc88',
    storageBucket: 'fitcare-6fc88.firebasestorage.app',
    iosBundleId: 'com.example.swHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNgs-uKahUukr_KnMCdS-9Wt4oMEZnSY',
    appId: '1:593815115508:ios:f17bf181f96f6ed58d70a1',
    messagingSenderId: '593815115508',
    projectId: 'fitcare-6fc88',
    storageBucket: 'fitcare-6fc88.firebasestorage.app',
    iosBundleId: 'com.example.swHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW0-CjBTM2eYFyARXvafcXbSBWNgIiKs4',
    appId: '1:593815115508:web:a3a32e94609b676b8d70a1',
    messagingSenderId: '593815115508',
    projectId: 'fitcare-6fc88',
    authDomain: 'fitcare-6fc88.firebaseapp.com',
    storageBucket: 'fitcare-6fc88.firebasestorage.app',
    measurementId: 'G-4BLBQ0RWEN',
  );
}
